---

description: test of pretrained resnet50 model on resolution scan test dataset
descriptive_tags: ['res-scan']

test_dataset_id: 0004_tst_r_scan_plv2_res # second places resolution scan dataset
test_dataset_artifact_alias: latest

model_artifact_id: resnet50_pretrained
model_artifact_alias: latest

batch_size: 32  # dropped to 32 to try to fit on P4 card
num_workers: 4
pin_memory: True
crop_flag: False
dataset_split_key: test  # used to get to correct level of dataset dict (to mirror 'train'/'val' splits)
last_distortion_type_flag: res  # normally should be 'noise'
loss_func: CrossEntropyLoss
status_interval: 10000  # images
