---

description: test of (hopefully all) relevant models on midpoint-90 dataset
descriptive_tags: ['all-models', 'midpoint-90-test']

test_dataset_id: 0015-tst-midpoint90_noise
test_dataset_artifact_alias: latest

model_artifact_ids:
  - 0031-resnet18-oct_000_best_loss
  - 0031-resnet18-oct_001_best_loss
  - 0023-resnet18-oct_010_best_loss
  - 0023-resnet18-oct_011_best_loss
  - 0023-resnet18-oct_100_best_loss
  - 0023-resnet18-oct_101_best_loss
  - 0023-resnet18-oct_110_best_loss
  - 0023-resnet18-oct_111_best_loss

  - 0034-resnet18-midpoint_best_loss
  - 0035-resnet18-midpoint-90_best_loss

  - 0033-resnet18-endpoint_best_loss
  - 0035-resnet18-endpoint-90_best_loss

  - densenet161_pretrained
  - resnet50_pretrained
  - resnet50_pretrained

  - 0020-densenet161-full_range_best_loss
  - 0020-resnet50-full_range_best_loss
  - 0020-resnet18-full_range_best_loss


model_artifact_alias: latest

batch_size: 32
num_workers: 4
pin_memory: True
crop_flag: False
dataset_split_key: test  # used to get to correct level of dataset dict (to mirror 'train'/'val' splits)
#last_distortion_type_flag: noise  # normally should be 'noise'
loss_func: CrossEntropyLoss
status_interval: 10000  # images
