---

description: test of octant models on fr90 megaset 1
descriptive_tags: ['oct-models', 'full-range-90-test', 'fr90-megaset-1']

test_dataset_id: 0012-tst-full_range_90_mega_set_2_noise # full range 90 megaset #2
test_dataset_artifact_alias: latest

model_artifact_ids:
  - 0023-resnet18-oct_010_best_loss
  - 0023-resnet18-oct_011_best_loss
  - 0023-resnet18-oct_100_best_loss
  - 0023-resnet18-oct_101_best_loss
  - 0023-resnet18-oct_110_best_loss
  - 0023-resnet18-oct_111_best_loss
  - 0031-resnet18-oct_000_best_loss
  - 0031-resnet18-oct_001_best_loss

model_artifact_alias: latest

batch_size: 32
num_workers: 4
pin_memory: True
crop_flag: False
dataset_split_key: test  # used to get to correct level of dataset dict (to mirror 'train'/'val' splits)
#last_distortion_type_flag: noise  # normally should be 'noise'
loss_func: CrossEntropyLoss
status_interval: 10000  # images
