---

description: test of point models on megaset 1
descriptive_tags: ['point-models', 'full-range-90-test', 'fr90-megaset-1']

test_dataset_id: 0012-tst-full_range_90_mega_set_1_noise # full range 90 megaset #1
test_dataset_artifact_alias: latest

model_artifact_ids:
  - 0034-resnet18-midpoint_best_loss
  - 0033-resnet18-endpoint_best_loss
  - densenet161_pretrained
  - resnet50_pretrained
  - resnet50_pretrained

model_artifact_alias: latest

batch_size: 32
num_workers: 4
pin_memory: True
crop_flag: False
dataset_split_key: test  # used to get to correct level of dataset dict (to mirror 'train'/'val' splits)
#last_distortion_type_flag: noise  # normally should be 'noise'
loss_func: CrossEntropyLoss
status_interval: 10000  # images
