---

description: test of key resnet18 models on undistorted dataset
descriptive_tags: ['rn18-key-models']

test_dataset_id: val_256 # undistorted test dataset
test_dataset_artifact_alias: v1

model_artifact_ids:
  - resnet18_pretrained
  - 0034-resnet18-midpoint_best_loss
  - 0033-resnet18-endpoint_best_loss
  - 0020-resnet18-full_range_best_loss

model_artifact_alias: latest

batch_size: 32
num_workers: 4
pin_memory: True
crop_flag: False
dataset_split_key: test  # used to get to correct level of dataset dict (to mirror 'train'/'val' splits)
#last_distortion_type_flag: noise  # normally should be 'noise'
loss_func: CrossEntropyLoss
status_interval: 10000  # images
