---

description: test of (hopefully last) relevant model on mp90 dataset. Last run duplicated rn50_pretrained test
descriptive_tags: ['resnet18', 'mp90-test']

test_dataset_id: 0015-tst-midpoint90_noise # mp90 test dataset
test_dataset_artifact_alias: latest

model_artifact_ids:
  - resnet18_pretrained

model_artifact_alias: latest

batch_size: 32
num_workers: 4
pin_memory: True
crop_flag: False
dataset_split_key: test  # used to get to correct level of dataset dict (to mirror 'train'/'val' splits)
#last_distortion_type_flag: noise  # normally should be 'noise'
loss_func: CrossEntropyLoss
status_interval: 10000  # images
