---

description: test last two octant models (000 and 001)
descriptive_tags: ['oct-models', 'full-range-test', '000-001-completed']

test_dataset_id: 0008-tst-full_range_mega_set_2_noise # full range megaset #2
test_dataset_artifact_alias: latest

model_artifact_ids:
#  - 0023-resnet18-oct_000  # abbreviated due to slow training run (likely a sporc config/job allocation issue)
#  - 0023-resnet18-oct_001 # abbreviated due to slow training run (likely a sporc config/job allocation issue)
#  - 0023-resnet18-oct_010_best_loss
#  - 0023-resnet18-oct_011_best_loss
#  - 0023-resnet18-oct_100_best_loss
#  - 0023-resnet18-oct_101_best_loss
#  - 0023-resnet18-oct_110_best_loss
#  - 0023-resnet18-oct_111_best_loss
  - 0031-resnet18-oct_000_best_loss
  - 0031-resnet18-oct_001_best_loss

model_artifact_alias: latest

batch_size: 32
num_workers: 4
pin_memory: True
crop_flag: False
dataset_split_key: test  # used to get to correct level of dataset dict (to mirror 'train'/'val' splits)
#last_distortion_type_flag: noise  # normally should be 'noise'
loss_func: CrossEntropyLoss
status_interval: 10000  # images
