---

description: test of octant models fr90-megaset-1
descriptive_tags: ['octant-models', 'fr90-megaset-1']

test_dataset_id: 0012-tst-full_range_90_mega_set_1_noise # full range 90 megaset 1
test_dataset_artifact_alias: latest

model_artifact_ids:
  - 0012-resnet18_sat6-oct_000_best_loss
  - 0012-resnet18_sat6-oct_001_best_loss
  - 0012-resnet18_sat6-oct_010_best_loss
  - 0016-resnet18_sat6-oct_011_best_loss
  - 0012-resnet18_sat6-oct_100_best_loss
  - 0016-resnet18_sat6-oct_101_best_loss
  - 0016-resnet18_sat6-oct_110_best_loss
  - 0019-resnet18_sat6-oct_111_best_loss

model_artifact_alias: latest

batch_size: 64
num_workers: 4
pin_memory: True
crop_flag: False
dataset_split_key: test  # used to get to correct level of dataset dict (to mirror 'train'/'val' splits)
# last_distortion_type_flag: noise  # normally should be 'noise', but not used by test script I believe
loss_func: CrossEntropyLoss
status_interval: 10000  # images
