---

description: test point models models on full range test dataset
descriptive_tags: ['point-models', 'mega-set-2']

test_dataset_id: 0009-tst-full_range_mega_set_2_noise # full range mega-set #1
test_dataset_artifact_alias: latest

model_artifact_ids:
  - 0021-resnet18_sat6-midpoint_best_loss
  - 0020-resnet18_sat6-endpoint_best_loss

  - 0005-resnet18_sat6-pretrain_lower_lr_best_loss
  - 0005-densenet161_sat6-pretrain_lower_lr_best_loss
  - 0004-resnet50_sat6-pretrain_lower_lr_best_loss

model_artifact_alias: latest

batch_size: 64
num_workers: 4
pin_memory: True
crop_flag: False
dataset_split_key: test  # used to get to correct level of dataset dict (to mirror 'train'/'val' splits)
# last_distortion_type_flag: noise  # normally should be 'noise', but not used by test script I believe
loss_func: CrossEntropyLoss
status_interval: 10000  # images
