---

#result_id: "0017-rlt-densenet161_pretrained-0006-tst-r_fr_pl-b_fr_pl-n_fr_pl_noise"
#identifier: 'DN161-pre-trained'

#result_id: "0018-rlt-resnet50_pretrained-0006-tst-r_fr_pl-b_fr_pl-n_fr_pl_noise"
#identifier: 'RN50-pre-trained'

#result_id: "0019-rlt-resnet18_pretrained-0006-tst-r_fr_pl-b_fr_pl-n_fr_pl_noise:v0"
#identifier: 'RN50-pre-trained'
#
#result_id: "0012-rlt-0001-mdl-resnet50_sat6_best_loss-0008-tst-r_fr_s6-b_fr_s6-n_fr_s6_noise"  # sat6
#identifier: 'RN50-pre-trained'

#result_id: "0011-rlt-0001-mdl-densenet161_sat6_best_loss-0008-tst-r_fr_s6-b_fr_s6-n_fr_s6_noise"  # sat6
#identifier: 'RN161-pre-trained'

#result_id: "0010-rlt-0000_mdl_best_loss-0008-tst-r_fr_s6-b_fr_s6-n_fr_s6_noise"  # sat6
#identifier: 'RN18-pre-trained'

#result_id: 0013-rlt-0003-resnet50_sat6-pretrain_lower_lr-0008-tst-r_fr_s6-b_fr_s6-n_fr_s6_noise  # sat6
#identifier: 'RN50-pt-low-lr-early-stop'

#result_id: 0014-rlt-0004-resnet50_sat6-pretrain_lower_lr_best_loss-0008-tst-r_fr_s6-b_fr_s6-n_fr_s6_noise  # sat6
#identifier: 'RN50-pt-low-lr'

#result_id: 0015-rlt-0005-resnet50_sat6-full_range_best_loss-0008-tst-r_fr_s6-b_fr_s6-n_fr_s6_noise:v0
#identifier: 'RN50-full-range'

#result_id: 0020-rlt-0003-resnet18-full_range_1_epoch_best_loss-0006-tst-r_fr_pl-b_fr_pl-n_fr_pl_noise:v0
#identifier: 'RN18-full-range_v0'

#result_id: 0019-rlt-0008-resnet18_sat6-full_range_best_loss-0008-tst-r_fr_s6-b_fr_s6-n_fr_s6_noise:v0
#identifier: 'RN18-full-range'

#result_id: 0018-rlt-0008-resnet50_sat6-full_range_v2_best_loss-0008-tst-r_fr_s6-b_fr_s6-n_fr_s6_noise:v0
#identifier: 'RN50-full-range-v2'

#result_id: 0017-rlt-0005-resnet50_sat6-full_range_best_loss-0008-tst-r_fr_s6-b_fr_s6-n_fr_s6_noise
#identifier: 'RN50-full-range'

#result_id: 0026-rlt-0020-resnet18-full_range_best_loss-0006-tst-r_fr_pl-b_fr_pl-n_fr_pl_noise:v0
#identifier: RN-full-range

#result_id: 0098-rlt-0033-resnet18-endpoint_best_loss-0008-tst-full_range_mega_set_2_noise:v0
#identifier: RN-endpoint

#result_id: 0097-rlt-0034-resnet18-midpoint_best_loss-0008-tst-full_range_mega_set_2_noise:v0
#identifier: DN-midpoint

#result_id: 0090-rlt-0020-resnet18_sat6-endpoint_best_loss-0012-tst-full_range_90_mega_set_1_noise:v0
#identifier: RN18-endpoint

#result_id: 0071-rlt-0005-resnet18_sat6-pretrain_lower_lr_best_loss-0008-tst-r_fr_s6-b_fr_s6-n_fr_s6_noise:v0
#identifier: RN18-pre-trained

#result_id: 0095-rlt-0005-resnet18_sat6-pretrain_lower_lr_best_loss-0012-tst-full_range_90_mega_set_1_noise:v0
#identifier: RN18-pre-trained

result_id: 0110-rlt-0022-resnet18_sat6-midpoint-90_best_loss-0012-tst-full_range_90_mega_set_1_noise:v0
identifier: RN18-midpoint
