---

description: test of pre-trained model on tiny (64 image) res, blur, noise dataset
descriptive_tags: ['pre-trained-model', 'debug']

test_dataset_id: 0005tst-coco_rbn_checkout-res-blur-noise:v0
test_dataset_artifact_alias: latest

model_artifact_id:  'fasterrcnn_resnet50_fpn'
model_artifact_alias: latest

batch_size: 16
num_workers: 4
pin_memory: True

status_interval: 16  # images


#rgb_flag: False
#dataset_split_key: test  # used to get to correct level of dataset dict (to mirror 'train'/'val' splits)
#last_distortion_type_flag: noise  # normally should be 'noise'
#loss_func: CrossEntropyLoss
