---

identifier: composite-result-test
parent_dir: default
overwrite_extracted_props: True

performance_prediction_result_ids:
  - 0019-rlt-0008-resnet18_sat6-full_range_best_loss-0008-tst-r_fr_s6-b_fr_s6-n_fr_s6_noise:v0
  - 0018-rlt-0008-resnet50_sat6-full_range_v2_best_loss-0008-tst-r_fr_s6-b_fr_s6-n_fr_s6_noise:v0

performance_eval_result_ids:
  - 0019-rlt-0008-resnet18_sat6-full_range_best_loss-0008-tst-r_fr_s6-b_fr_s6-n_fr_s6_noise:v0
  - 0018-rlt-0008-resnet50_sat6-full_range_v2_best_loss-0008-tst-r_fr_s6-b_fr_s6-n_fr_s6_noise:v0


