---

identifier: composite-result-test
parent_dir: default
overwrite_extracted_props: True

performance_prediction_result_ids:
#  - 0019-rlt-0008-resnet18_sat6-full_range_best_loss-0008-tst-r_fr_s6-b_fr_s6-n_fr_s6_noise:v0
#  - 0018-rlt-0008-resnet50_sat6-full_range_v2_best_loss-0008-tst-r_fr_s6-b_fr_s6-n_fr_s6_noise:v0
  - '0034-rlt-0019-resnet18_sat6-oct_111_best_loss-0008-tst-r_fr_s6-b_fr_s6-n_fr_s6_noise:v0'
  - '0033-rlt-0016-resnet18_sat6-oct_110_best_loss-0008-tst-r_fr_s6-b_fr_s6-n_fr_s6_noise:v0'
  - '0032-rlt-0016-resnet18_sat6-oct_101_best_loss-0008-tst-r_fr_s6-b_fr_s6-n_fr_s6_noise:v0'
  - '0031-rlt-0012-resnet18_sat6-oct_100_best_loss-0008-tst-r_fr_s6-b_fr_s6-n_fr_s6_noise:v0'
  - '0030-rlt-0016-resnet18_sat6-oct_011_best_loss-0008-tst-r_fr_s6-b_fr_s6-n_fr_s6_noise:v0'
  - '0029-rlt-0012-resnet18_sat6-oct_010_best_loss-0008-tst-r_fr_s6-b_fr_s6-n_fr_s6_noise:v0'
  - '0028-rlt-0012-resnet18_sat6-oct_001_best_loss-0008-tst-r_fr_s6-b_fr_s6-n_fr_s6_noise:v0'
  - '0026-rlt-0012-resnet18_sat6-oct_000_best_loss-0008-tst-r_fr_s6-b_fr_s6-n_fr_s6_noise:v0'

performance_eval_result_ids:
  - 0042-rlt-0019-resnet18_sat6-oct_111_best_loss-0009-tst-full_range_mega_set_2_noise:v0
  - 0041-rlt-0016-resnet18_sat6-oct_110_best_loss-0009-tst-full_range_mega_set_2_noise:v0
  - 0040-rlt-0016-resnet18_sat6-oct_101_best_loss-0009-tst-full_range_mega_set_2_noise:v0
  - 0039-rlt-0012-resnet18_sat6-oct_100_best_loss-0009-tst-full_range_mega_set_2_noise:v0
  - 0038-rlt-0016-resnet18_sat6-oct_011_best_loss-0009-tst-full_range_mega_set_2_noise:v0
  - 0037-rlt-0012-resnet18_sat6-oct_010_best_loss-0009-tst-full_range_mega_set_2_noise:v0
  - 0036-rlt-0012-resnet18_sat6-oct_001_best_loss-0009-tst-full_range_mega_set_2_noise:v0
  - 0035-rlt-0012-resnet18_sat6-oct_000_best_loss-0009-tst-full_range_mega_set_2_noise:v0

