---

train_dataset_id: '0002-trn-train'
train_dataset_artifact_alias: latest

starting_model_id: '0005-resnet18_sat6-pretrain_lower_lr_best_loss'
starting_model_artifact_alias: 'latest'

crop_flag: False
distortion_tags: ['rt_fr_s6', 'bt_fr_s6', 'nt_fr_s6']
descriptive_tags: ['full_range']
num_epochs: 30
batch_size: 64
num_workers: 8
pin_memory: True
optimizer: 'Adam'
lr: 0.00005  # Adam default = 0.001
loss_func: 'CrossEntropyLoss'
description: train full range resnet18 model
artifact_type: 'model'

name_string: 'full_range'  # set to null or comment out line to name model using distortion tags
