---

train_dataset_id: '0000_numpy'
train_dataset_artifact_alias: latest

starting_model_id: '0001'
starting_model_artifact_alias: 'best'

rgb_flag: False
distortion_tags: ['rst4', 'b5', 'nf5']
descriptive_tags: ['endpoint']
num_epochs: 5
batch_size: 32
num_workers: 4
pin_memory: True
optimizer: 'Adam'
loss_func: 'CrossEntropyLoss'
description: 'tune the best no-distortion model against endpoint distortion dataset'
artifact_type: 'model'
