---

train_dataset_id: '0000_numpy'
train_dataset_artifact_alias: latest

starting_model_id: '0001'
starting_model_artifact_alias: 'best'

rgb_flag: False
distortion_tags: ['rst2', 'b11', 'nf10']
descriptive_tags: []
num_epochs: 5
batch_size: 32
num_workers: 4
pin_memory: True
optimizer: 'Adam'
loss_func: 'CrossEntropyLoss'
description: 'tune the best no-distortion model against mid-band distortion dataset (midpoint +- 25-percent)'
artifact_type: 'model'
