---

train_dataset_id: '0001-trn-train'
train_dataset_artifact_alias: latest

starting_model_id: 'resnet18_sat6'
starting_model_artifact_alias: 'latest'

crop_flag: False
distortion_tags: ['rt_fr_s6', 'bt_fr_s6', 'nt_fr_s6']
descriptive_tags: ['full-range-checkout']
num_epochs: 10  # 30
batch_size: 32  # 64
num_workers: 8
pin_memory: True
optimizer: 'Adam'
lr: 0.0001  # Adam default = 0.001
loss_func: 'CrossEntropyLoss'
description: 'train a full range sat6 model on an abbreviated dataset to debug'
artifact_type: 'model'

