---

train_dataset_id: 0023trn-coco_fr_train:v0
train_dataset_artifact_alias: latest

starting_model_id: fasterrcnn_resnet50_fpn
starting_model_artifact_alias: latest
distortion_tags: []

num_epochs: 1
batch_size: 6
num_workers: 4

optimizer_type: SGD
lr: 0.005
momentum: 0.9
weight_decay: 0.0005

status_interval: 1000

description: training on basic coco noise dataset
artifact_type: model

device: 6

name_string: rcnn-fr-1x-10e # later manually changed artifact name to 0002yolo-yolov8-noise_best_loss:v0

