
---

train_dataset_id: 0036trn-coco_fr90_tr_checkout:v0
train_dataset_artifact_alias: latest

starting_model_id: fasterrcnn_resnet50_fpn
starting_model_artifact_alias: latest
distortion_tags: []

num_epochs: 1
batch_size: 4
num_workers: 0

optimizer_type: SGD
lr: 0.005
momentum: 0.9
weight_decay: 0.0005

status_interval: 100

description: debug
artifact_type: model

name_string: rcnn-debug

device: 1


