---

#model_id: 'densenet161_places365_as_downloaded'
#new_model_id: 'densenet161_pretrained'
#new_model_filename: 'densenet161.pt'
#description: 'logging pre-trained places365 densenet model'


#model_id: 'densenet161_sat6'
#new_model_id: 'densenet161_sat6'
#new_model_filename: 'densenet161.pt'
#description: 'logging densenet model'

model_id: 'resnet50_sat6'
new_model_id: 'resnet50_sat6'
new_model_filename: 'resnet50.pt'
description: 'logging resnet50 sat6 model'
