---

description: test of pre-trained model on noise scan dataset, run on local machine because of sporc env issues
descriptive_tags: ['pre-trained-model', 'noise-scan-dataset']

test_dataset_id: 0044tst-coco_n_scan-noise:v0
test_dataset_artifact_alias: latest

model_artifact_id:  'fasterrcnn_resnet50_fpn'
model_artifact_alias: latest

batch_size: 2
num_workers: 0
pin_memory: True

status_interval: 500  # images


#rgb_flag: False
#dataset_split_key: test  # used to get to correct level of dataset dict (to mirror 'train'/'val' splits)
#last_distortion_type_flag: noise  # normally should be 'noise'
#loss_func: CrossEntropyLoss
