---

description: debugging yolo test script on mini dataset
descriptive_tags: ['pre-trained-model']

test_dataset_id:  0012tst-val2017-mini-no_dist:v0
test_dataset_artifact_alias: latest

model_artifact_id: yolov8n
model_artifact_alias: latest

batch_size: 2
num_workers: 0
pin_memory: True

status_interval: 500  # images


#rgb_flag: False
#dataset_split_key: test  # used to get to correct level of dataset dict (to mirror 'train'/'val' splits)
#last_distortion_type_flag: noise  # normally should be 'noise'
#loss_func: CrossEntropyLoss
