---

identifier: composite-result-test
parent_dir: default
overwrite_extracted_props: True

performance_prediction_result_ids:
  - 0053-rlt-0023-resnet18-oct_111_best_loss-0006-tst-r_fr_pl-b_fr_pl-n_fr_pl_noise:v0
  - 0052-rlt-0023-resnet18-oct_110_best_loss-0006-tst-r_fr_pl-b_fr_pl-n_fr_pl_noise:v0
  - 0051-rlt-0023-resnet18-oct_101_best_loss-0006-tst-r_fr_pl-b_fr_pl-n_fr_pl_noise:v0
  - 0050-rlt-0023-resnet18-oct_100_best_loss-0006-tst-r_fr_pl-b_fr_pl-n_fr_pl_noise:v0
  - 0049-rlt-0023-resnet18-oct_011_best_loss-0006-tst-r_fr_pl-b_fr_pl-n_fr_pl_noise:v0
  - 0048-rlt-0023-resnet18-oct_010_best_loss-0006-tst-r_fr_pl-b_fr_pl-n_fr_pl_noise:v0
  - 0047-rlt-0023-resnet18-oct_001-0006-tst-r_fr_pl-b_fr_pl-n_fr_pl_noise:v0
  - 0046-rlt-0023-resnet18-oct_000-0006-tst-r_fr_pl-b_fr_pl-n_fr_pl_noise:v0

performance_eval_result_ids:
  - 0045-rlt-0023-resnet18-oct_111_best_loss-0008-tst-full_range_mega_set_2_noise:v0
  - 0043-rlt-0023-resnet18-oct_110_best_loss-0008-tst-full_range_mega_set_2_noise:v0
  - 0041-rlt-0023-resnet18-oct_101_best_loss-0008-tst-full_range_mega_set_2_noise:v0
  - 0039-rlt-0023-resnet18-oct_100_best_loss-0008-tst-full_range_mega_set_2_noise:v0
  - 0037-rlt-0023-resnet18-oct_011_best_loss-0008-tst-full_range_mega_set_2_noise:v0
  - 0035-rlt-0023-resnet18-oct_010_best_loss-0008-tst-full_range_mega_set_2_noise:v0
  - 0033-rlt-0023-resnet18-oct_001-0008-tst-full_range_mega_set_2_noise:v0
  - 0031-rlt-0023-resnet18-oct_000-0008-tst-full_range_mega_set_2_noise:v0


