---

description: noise scan test dataset to find the noise level at which pre-trained performance drops to chance

parent_dataset_id: sat6_full
parent_artifact_alias: latest
parent_artifact_filename: standard  # standard functions as a flag to use definitions.STANDARD_ARTIFACT_FILENAME

num_images: 'all'
images_per_file: 1000
distortion_tags: ['n_scan']
distortion_type_flags: ['noise']  # specifies distortion_tags associated distortion types
iterations: 1
artifact_type: test_dataset
dataset_split_key: test  # used to mirror 'train'/'val' split in data structure
artifact_filename: standard
datatype_key: np.uint8

