---

description: test of resnet18 endpoint-90 model on places full-range-90 megaset-1
descriptive_tags: ['ep90', 'full-range-90']

test_dataset_id: 0012-tst-full_range_90_mega_set_1_noise
test_dataset_artifact_alias: latest

model_artifact_id: resnet18_pretrained
model_artifact_alias: latest

batch_size: 32
num_workers: 4
pin_memory: True
crop_flag: False
dataset_split_key: test  # used to get to correct level of dataset dict (to mirror 'train'/'val' splits)
last_distortion_type_flag: noise  # normally should be 'noise'
loss_func: CrossEntropyLoss
status_interval: 10000  # images
