---

description: test of full-range resnet18 model on endpoint dataset

descriptive_tags: ['rn18-full-range', 'endpoint-test']

test_dataset_id: 0011-tst-endpoint_noise  # ep90 dataset
test_dataset_artifact_alias: latest

model_artifact_id: 0011-resnet18_sat6-full_range_best_loss
model_artifact_alias: latest

batch_size: 64
num_workers: 4
pin_memory: True
crop_flag: False
dataset_split_key: test  # used to get to correct level of dataset dict (to mirror 'train'/'val' splits)
last_distortion_type_flag: noise  # normally should be 'noise'
loss_func: CrossEntropyLoss
status_interval: 10000  # images
