---

description: test of mp-90 model on fr90 megaset-1

descriptive_tags: ['mp-90', 'fr90-test']

test_dataset_id:  0012-tst-full_range_90_mega_set_1_noise  # fr90-megaset-1
test_dataset_artifact_alias: latest

model_artifact_id: 0022-resnet18_sat6-midpoint-90_best_loss
model_artifact_alias: latest

batch_size: 64
num_workers: 4
pin_memory: True
crop_flag: False
dataset_split_key: test  # used to get to correct level of dataset dict (to mirror 'train'/'val' splits)
last_distortion_type_flag: noise  # normally should be 'noise'
loss_func: CrossEntropyLoss
status_interval: 10000  # images
