---

description: test of no-distortion resnet50 model from an early training epoch to see if over-fitting is decreased
#descrptive_tags: ['noise-scan']

test_dataset_id:  0008-tst-r_fr_s6-b_fr_s6-n_fr_s6_noise # full range mega-set
test_dataset_artifact_alias: latest

model_artifact_id: 0001-mdl-resnet50_sat6
model_artifact_alias: v0 # CHECKING EARLY STOP (hence not 'latest')

batch_size: 64
num_workers: 4
pin_memory: True
crop_flag: False
dataset_split_key: test  # used to get to correct level of dataset dict (to mirror 'train'/'val' splits)
last_distortion_type_flag: noise  # normally should be 'noise'
loss_func: CrossEntropyLoss
status_interval: 10000  # images
