---

description: test of no-distortion model on noise scan v3 test dataset
descrptive_tags: ['noise-scan']

test_dataset_id: 0006_tst_n_scan_v3_pan # noise scan dataset
test_dataset_artifact_alias: latest

model_artifact_id: 0000_mdl_best_loss
model_artifact_alias: latest

batch_size: 64
num_workers: 4
pin_memory: True
crop_flag: False
dataset_split_key: test  # used to get to correct level of dataset dict (to mirror 'train'/'val' splits)
last_distortion_type_flag: noise  # normally should be 'noise'
loss_func: CrossEntropyLoss
status_interval: 10000  # images
