---

description: test of no-distortion model on resolution scan test dataset
descrptive_tags: ['res-scan']

test_dataset_id: 0000_tst_r_scan_res # resolution scan dataset
test_dataset_artifact_alias: latest

model_artifact_id: 0000_mdl_best_loss
model_artifact_alias: latest

batch_size: 64
num_workers: 0
pin_memory: True
rgb_flag: False
dataset_split_key: test  # used to get to correct level of dataset dict (to mirror 'train'/'val' splits)
last_distortion_type_flag: res  # normally should be 'noise'
loss_func: CrossEntropyLoss
status_interval: 10000  # images
