---

description: test of endpoint model on full range mega-set
descrptive_tags: ['full-range-mega-set', 'endpoint-model']

test_dataset_id: 0040_tst_rs1_bcs3_nfs3_noise # full range mega-set
test_dataset_artifact_alias: latest

#model_artifact_id: "0001"
#model_artifact_alias: best # this alias only applies for the 0001 model

#model_artifact_id: 0028_mdl_rst2_b11_nf10_best_loss # mid-band model
#model_artifact_alias: latest

#model_artifact_id: 0027_mdl_rst1_b10_nf11_best_loss # full range model
#model_artifact_alias: latest

model_artifact_id: 0030_mdl_rst4_b5_nf5_best_loss # endpoint
model_artifact_alias: latest

batch_size: 32
num_workers: 0
pin_memory: True
rgb_flag: False
dataset_split_key: test  # used to get to correct level of dataset dict (to mirror 'train'/'val' splits)
last_distortion_type_flag: noise  # normally should be 'noise'
loss_func: CrossEntropyLoss
status_interval: 10000  # images
