---

description: test of res scan in updated distortion script

parent_dataset_id: val_256
parent_artifact_alias: latest
parent_artifact_filename: standard  # standard functions as a flag to use definitions.STANDARD_ARTIFACT_FILENAME

num_images: 2048
images_per_file: 64
distortion_tags: ['r_scan_pl']
distortion_type_flags: ['res']  # specifies distortion_tags associated distortion types
iterations: 1
artifact_type: test_dataset
dataset_split_key: test  # used to mirror 'train'/'val' split in data structure
artifact_filename: standard
datatype_key: np.uint8

image_shape: [256, 256, 3]  # only used by places scripts
