---

train_dataset_id: 0033trn-coco_ep90_tr_debug
train_dataset_artifact_alias: latest

starting_model_id: yolov8m
starting_model_artifact_alias: latest
distortion_tags: []

num_epochs: 1
batch_size: 1
num_workers: 4

description: training on coco ep-debug dataset
artifact_type: 'model'

name_string: v8l-fr-ep-debug  # later manually changed artifact name to 0002yolo-yolov8-noise_best_loss:v0

