---

train_dataset_id: 0019trn-coco_noise_train_checkout:v0
train_dataset_artifact_alias: latest

starting_model_id: 'yolov8n'
starting_model_artifact_alias: 'latest'
distortion_tags: []

num_epochs: 5
batch_size: 16
num_workers: 4

description: training on basic coco noise dataset
artifact_type: 'model'

name_string: yolov8n-noise  # later manually changed artifact name to 0002yolo-yolov8-noise_best_loss:v0

