---

train_dataset_id: 0030trn-coco_oct101_tr
train_dataset_artifact_alias: latest

starting_model_id: 0023yolo-v8l-fr_best_loss:v0
starting_model_artifact_alias: latest
distortion_tags: []

num_epochs: 10
batch_size: 8
num_workers: 4

description: training on coco octant 101 dataset
artifact_type: model

name_string: v8l-oct101

