---

train_dataset_id: 0033trn-coco_mp90_tr:v0
train_dataset_artifact_alias: latest

starting_model_id: 0038yolo-v8l-mp_best_loss:v0
starting_model_artifact_alias: latest
distortion_tags: []

num_epochs: 45
batch_size: 8
num_workers: 4

description: extending training on coco midpoint90 dataset
artifact_type: 'model'

name_string: v8l-mp-ext
device: 2
