---

train_dataset_id: 0027trn-coco_oct010_tr
train_dataset_artifact_alias: latest

starting_model_id: 0000yolo-v8l-oct010_best_loss:v0
starting_model_artifact_alias: latest
distortion_tags: []

num_epochs: 40
batch_size: 8
num_workers: 2

description: extending training on coco octant 010 dataset
artifact_type: model

name_string: v8l-oct010-ext

