---

train_dataset_id: 0023trn-coco_fr_train:v0
train_dataset_artifact_alias: latest

starting_model_id: 'yolov8l'
starting_model_artifact_alias: 'latest'
distortion_tags: []

num_epochs: 10
batch_size: 8
num_workers: 4
learning_rate: 0.005

description: training on coco fr dataset with lower learning rate and double the number of epochs
artifact_type: 'model'

name_string: v8l-fr-llr

