---

train_dataset_id: 0023trn-coco_fr_train:v0
train_dataset_artifact_alias: latest

starting_model_id: 'yolov8l'
starting_model_artifact_alias: 'latest'
distortion_tags: []

num_epochs: 5
batch_size: 8
num_workers: 4

description: training on coco fr dataset
artifact_type: 'model'

name_string: v8l-fr  # later manually changed artifact name to 0002yolo-yolov8-noise_best_loss:v0

