---

train_dataset_id: 0033trn-coco_oct110_tr:v0  # dataset created out of order
train_dataset_artifact_alias: latest

starting_model_id: 0000yolo-v8l-oct110_best_loss:v0
starting_model_artifact_alias: latest
distortion_tags: []

num_epochs: 40
batch_size: 8
num_workers: 2

description: extending training on coco octant 110 dataset
artifact_type: model

name_string: v8l-oct110-ext

