---

train_dataset_id: 0025trn-coco_oct000_tr
train_dataset_artifact_alias: latest

starting_model_id: 0023yolo-v8l-fr_best_loss:v0
starting_model_artifact_alias: latest
distortion_tags: []

num_epochs: 1
batch_size: 8
num_workers: 4

description: training on coco octant 000 dataset
artifact_type: model

name_string: v8l-oct000-dry-run

