---

train_dataset_id: 0029trn-coco_oct100_tr
train_dataset_artifact_alias: latest

starting_model_id: 0000yolo-v8l-oct100_best_loss:v0
starting_model_artifact_alias: latest
distortion_tags: []

num_epochs: 40
batch_size: 8
num_workers: 4

description: extending training on coco octant 100 dataset
artifact_type: model

name_string: v8l-oct100-ext

