---

train_dataset_id: 0034trn-coco_ep90_tr:v0
train_dataset_artifact_alias: latest

starting_model_id: 0039yolo-v8l-ep_best_loss:v0
starting_model_artifact_alias: latest
distortion_tags: []

num_epochs: 45
batch_size: 8
num_workers: 4

description: extending training on coco endpoint90 dataset
artifact_type: 'model'

name_string: v8l-ep-ext
device: 1
