---

train_dataset_id: 0024trn-coco_fr_train_10x:v0
train_dataset_artifact_alias: latest

starting_model_id: 'yolov8m'
starting_model_artifact_alias: 'latest'
distortion_tags: []

num_epochs: 1
batch_size: 8
num_workers: 4

description: training 1 epoch on on coco fr-10x (10 distortion iteration) dataset
artifact_type: model

name_string: v8m-fr10x-1e  # later manually changed artifact name to 0002yolo-yolov8-noise_best_loss:v0

