---

train_dataset_id: '0002-trn-train'
train_dataset_artifact_alias: latest

starting_model_id: '0011-resnet18_sat6-full_range_best_loss'
starting_model_artifact_alias: 'latest'

crop_flag: False
distortion_tags: ['rt_0_s6', 'bt_1_s6', 'nt_1_s6']
descriptive_tags: ['octant-011']
num_epochs: 30
batch_size: 64
num_workers: 8
pin_memory: True
optimizer: 'Adam'
lr: 0.00005  # Adam default = 0.001
loss_func: 'CrossEntropyLoss'
description: train octant 011 resnet18 model
artifact_type: 'model'

name_string: 'oct_011'  # set to null or comment out line to name model using distortion tags
