---

identifier: fr-ext-m1-m2

performance_prediction_result_id_pairs:
  - ['0060rlt-0060yolo-v8l-fr-ext_best_loss-0054tst-coco_fr90:v0', 'megaset-1' ]

performance_eval_result_ids_pairs:
  - ['0064rlt-0060yolo-v8l-fr-ext_best_loss-0055tst-coco_fr90_mega-2:v0', 'megaset-2']

